INSERT INTO `store` (`name`, `description`, `address`) VALUES
('Loja Central', 'Loja de eletrônicos e acessórios', 'Rua das Lojas, 123'),
('Tech Point', 'Especializada em informática', 'Av. Principal, 456'),
('Mega Store', 'Super loja com diversos produtos', 'Rua Comercial, 789'),
('Fashion Moda', 'Roupas e acessórios femininos', 'Rua da Moda, 101'),
('Supermercado Verde', 'Alimentos frescos e orgânicos', 'Av. Brasil, 202'),
('Auto Peças Express', 'Peças automotivas e acessórios', 'Rua dos Motores, 303'),
('Games & Geek', 'Loja especializada em jogos e cultura geek', 'Av. GameWorld, 404'),
('Livraria do Saber', 'Livros e materiais escolares', 'Rua das Letras, 505'),
('Pet Shop Amigos', 'Rações e produtos para pets', 'Av. Animal, 606'),
('Casa e Construção', 'Materiais para casa e construção', 'Rua dos Materiais, 707'),
('Papelaria Criativa', 'Papelaria e artigos para escritório', 'Av. Criativa, 808'),
('Moda Masculina', 'Roupas e acessórios masculinos', 'Rua dos Homens, 909'),
('Baby Store', 'Produtos para bebês', 'Av. Mamãe, 111'),
('Esporte Total', 'Materiais esportivos', 'Rua do Atleta, 222'),
('Beleza & Estética', 'Cosméticos e produtos de beleza', 'Av. Beleza, 333'),
('Tech Solutions', 'Soluções tecnológicas', 'Rua da Tecnologia, 444'),
('Farmácia Popular', 'Medicamentos e produtos farmacêuticos', 'Av. Saúde, 555'),
('Bike Mania', 'Loja especializada em bicicletas', 'Rua das Bikes, 666'),
('Joalheria Elegance', 'Joias e acessórios finos', 'Av. Ouro, 777'),
('Doces & Delícias', 'Confeitaria e doces artesanais', 'Rua das Delícias, 888'),
('Móveis Planejados', 'Móveis sob medida', 'Av. Decoração, 999'),
('Mercadinho do Bairro', 'Produtos básicos e essenciais', 'Rua da Feira, 112'),
('Chocolateria Premium', 'Chocolates gourmet', 'Av. Cacau, 223'),
('Relojoaria Fina', 'Relógios e acessórios', 'Rua do Tempo, 334'),
('Brinquedos e Fantasia', 'Loja de brinquedos e fantasias', 'Av. da Criança, 445'),
('Mundo Fitness', 'Equipamentos e suplementos fitness', 'Rua Fit, 556'),
('Ferramentas e Utilidades', 'Ferramentas para casa e oficina', 'Av. do Trabalho, 667'),
('Luminárias e Iluminação', 'Luminárias modernas e clássicas', 'Rua da Luz, 778'),
('Casa do Pescador', 'Artigos para pesca e camping', 'Av. Aventura, 889'),
('Moda Plus Size', 'Roupas para todos os tamanhos', 'Rua Estilo, 990');
